
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.KeyStroke;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alberto Ocaranza
 */
import FileManager.FileManager;
import javax.swing.JOptionPane;
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private FileManager fm = new FileManager(this);
    public Main() {
        initComponents();
        // Configurar atajos de teclado
        subOpen.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_O, ActionEvent.CTRL_MASK));
        subSave.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, ActionEvent.CTRL_MASK));
        subSaveAs.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, ActionEvent.CTRL_MASK + ActionEvent.ALT_MASK));
        subCloseFile.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_X, ActionEvent.CTRL_MASK + ActionEvent.SHIFT_MASK));
        // Set al titulo
        this.setTitle("Gypsy");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaContent = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        itemFile = new javax.swing.JMenu();
        subNewFile = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        subOpen = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        subSave = new javax.swing.JMenuItem();
        subSaveAs = new javax.swing.JMenuItem();
        subCloseFile = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        itemEdit = new javax.swing.JMenu();
        itemFormat = new javax.swing.JMenu();
        itemTools = new javax.swing.JMenu();
        itemAbout = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));

        txtaContent.setColumns(20);
        txtaContent.setRows(5);
        txtaContent.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtaContentCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(txtaContent);

        itemFile.setMnemonic('c');
        itemFile.setText("Archivo");
        itemFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFileActionPerformed(evt);
            }
        });

        subNewFile.setText("Nuevo");
        subNewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subNewFileActionPerformed(evt);
            }
        });
        itemFile.add(subNewFile);
        itemFile.add(jSeparator1);

        subOpen.setMnemonic('o');
        subOpen.setText("Abrir");
        subOpen.setToolTipText("");
        subOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subOpenActionPerformed(evt);
            }
        });
        itemFile.add(subOpen);

        jMenuItem5.setText("Abrir recientes");
        itemFile.add(jMenuItem5);
        itemFile.add(jSeparator2);

        subSave.setMnemonic('s');
        subSave.setText("Guardar");
        subSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subSaveActionPerformed(evt);
            }
        });
        itemFile.add(subSave);

        subSaveAs.setMnemonic('s');
        subSaveAs.setText("Guardar como");
        subSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subSaveAsActionPerformed(evt);
            }
        });
        itemFile.add(subSaveAs);

        subCloseFile.setMnemonic('x');
        subCloseFile.setText("Cerrar archivo");
        subCloseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCloseFileActionPerformed(evt);
            }
        });
        itemFile.add(subCloseFile);
        itemFile.add(jSeparator3);

        jMenuItem8.setText("Salir");
        itemFile.add(jMenuItem8);

        jMenuBar1.add(itemFile);

        itemEdit.setText("Editar");
        jMenuBar1.add(itemEdit);

        itemFormat.setText("Formato");
        jMenuBar1.add(itemFormat);

        itemTools.setText("Herramientas");
        jMenuBar1.add(itemTools);

        itemAbout.setText("Acerca de");
        jMenuBar1.add(itemAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFileActionPerformed
        
    }//GEN-LAST:event_itemFileActionPerformed

    private void subNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subNewFileActionPerformed
        
    }//GEN-LAST:event_subNewFileActionPerformed

    private void subOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subOpenActionPerformed
        this.fm.isSaved = true;
        this.fm.openFile(txtaContent);
        this.setTitle("Gypsy - " + this.fm.fileURL);
    }//GEN-LAST:event_subOpenActionPerformed

    private void subSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subSaveAsActionPerformed
        String windowTitle = true ? this.fm.fileURL : this.fm.fileURL + "*";
        this.fm.saveAs(txtaContent);
        this.setTitle("Gypsy - " + windowTitle);
    }//GEN-LAST:event_subSaveAsActionPerformed

    private void subSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subSaveActionPerformed
        String windowTitle = true ? this.fm.fileURL : this.fm.fileURL + "*";
        this.fm.save(txtaContent);
        this.setTitle("Gypsy - " + windowTitle);
    }//GEN-LAST:event_subSaveActionPerformed

    private void txtaContentCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtaContentCaretUpdate
        this.fm.isSaved = false;
        if(this.fm.fileURL != null){
            String windowTitle = true ? this.fm.fileURL + "*" : this.fm.fileURL;
            this.setTitle("Gypsy - " + windowTitle);    
        }
        
    }//GEN-LAST:event_txtaContentCaretUpdate

    private void subCloseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCloseFileActionPerformed
        if(this.fm.fileURL != null){
            // Entonces se revisa si ya se guardó
            if(this.fm.isSaved == false){
                // Si no se ha guardado entonces se pregunta si quiere guardar
                // Mostrar pregunta para sobreescribir: si acepta sobreescribe, si no acepta se genera un nuevo nombre de archivo
            Object[] options = {"Guardar y cerrar", "Cerrar sin guardar"};
                    
            int n = JOptionPane.showOptionDialog(this,
                "¿Deseas salir sin guardar?",
                "Salir sin guardar",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                options,
                options[1]);
            // Manejar la opción de usuario
            if(n == 0){
                // Guardar
                this.fm.save(txtaContent);
                // Eliminar registros variables
                this.fm.isSaved = false;
                this.fm.fileURL = null;
                // Cambiar title
                this.setTitle("Gypsy");
                // Borrar area
                this.txtaContent.setText(null);
            }else if(n == 1){
                // Cambiar title
                this.setTitle("Gypsy");
                // Borrar area
                this.txtaContent.setText(null);
            }
            }else{
                // Si ya se guardó se cierra
                System.out.println("Cierra");
                txtaContent.setText(null);
                this.fm.fileURL = null;
                this.setTitle("Gypsy");    
            }
        }else{
            System.err.println("No hay nada por lo tanto no hace nada.");
        }
    }//GEN-LAST:event_subCloseFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu itemAbout;
    private javax.swing.JMenu itemEdit;
    private javax.swing.JMenu itemFile;
    private javax.swing.JMenu itemFormat;
    private javax.swing.JMenu itemTools;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem subCloseFile;
    private javax.swing.JMenuItem subNewFile;
    private javax.swing.JMenuItem subOpen;
    private javax.swing.JMenuItem subSave;
    private javax.swing.JMenuItem subSaveAs;
    private javax.swing.JTextArea txtaContent;
    // End of variables declaration//GEN-END:variables
}
